OTS/urls.py
from django.urls import path
from OTS.views import *
app_name='OTS'
urlpatterns=[
    path('',welcome),#landing page
    path('new-candidate',candidateRegistrationForm,name='registrationForm'),
    path('store-candidate',candidateRegistration,name='storeCandidate'),
    path('login',loginView,name='login'),
    path('home',candidateHome,name='userhome'),
    path('test-paper',testPaper,name='testpaper'),
    path('calculate-result',calculateTestResult,name='calculateTest'),
    path('test-history',testResultHistory,name='testHistory'),
    path('result',showTestResult,name='result'),
    path('logout',logoutView,name='logout'),

]

OTS/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model) :
    username = models.CharField(max_length=20,primary_key=True)
    password = models.CharField(null=False,max_length=20)
    name = models.CharField(null=False,max_length=20)#mtlb null nhi ho skta hai
    test_attempted=models.IntegerField(default=0)
    points =models.FloatField(default=0.0)

class Question(models.Model) :
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()#charfield has support upto 25 characters
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)

class Result(models.Model):
    result=models.BigAutoField(primary_key=True,auto_created=True)
    username =models.ForeignKey(Candidate,on_delete=models.CASCADE)#so agr primary key delete hogyi toh yaha se bhi records delete hone chahiye 
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()


      

OTS/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import *
from django.template import loader
from django.contrib.auth import logout
import random

# Create your views here.
def welcome(request):
    template=loader.get_template('welcome.html')
    return HttpResponse(template.render())



def candidateRegistrationForm(request):
    res = render(request,'registration_form.html')
    return res
    # template = loader.get_template('registration_form.html')
    # return HttpResponse(template.render())

def candidateRegistration(request):
    # jab form waha se submit hota hai tab request mei form data aata hai 
    if request.method=='POST':
        username=request.POST['username']
        #Check if the user already exists
        if(len(Candidate.objects.filter(username=username))) :
            userStatus=1#user already exists
        else :
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['password']
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2

    else:
        userStatus=3#iska mtlb hai ki method post nhi hai
    context={
        'userStatus':userStatus,
    }
    res=render(request,'registration.html',context)#kitne bhi bhej skte ho argumennts
    return res




        #POST ke naame ki and GET ke naam ki dictionary hoti hai request attribute mei
        #Aur unki keys woh name attribute ke value hote hai
    pass
def loginView(request):
    if(request.method=='POST'):
        username = request.POST['username']
        password = request.POST['password']
        candidate = Candidate.objects.filter(username=username,password=password)
        if(len(candidate)==0) :
            loginError="Invalid Username or Password"
            res = render(request,'login.html',{'loginError':loginError})#ye jab aapka login fail hoga tab call hoga
        else : 
            #login success
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name #used to store the username and name
            res=HttpResponseRedirect('home')
    else :
        res = render(request,'login.html')
    return res

def candidateHome(request):
    if 'name' not in request.session.keys() :#session storage pure file kei liye hota hai IMPORTANT HAI BAHOT PRIVACY KE LIYE WITHOUT DIRECT LINK ACCESS NHI HOGA
        res=HttpResponseRedirect('login')
    else :
        name=request.session['name']
        context={
            'name':name
        }
        res = render(request,'home.html',context)
    return res

def testPaper(request):
    if 'name' not in request.session.keys() :#session storage pure file kei liye hota hai IMPORTANT HAI BAHOT PRIVACY KE LIYE WITHOUT DIRECT LINK ACCESS NHI HOGA
        res=HttpResponseRedirect('login')
    #fetch question from database table
    n=int(request.GET['n'])# iski value url mei hogi
    question_pool = list(Question.objects.all())
    random.shuffle(question_pool)#it shuffles the element in list
    questions_list=question_pool[:n]#needs starting n questions
    context={
        'questions':questions_list,
    }
    return render(request,'test_paper.html',context)

def calculateTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect('login')
    total_attempt=0
    total_wrong=0
    total_right=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list :
        question=Question.objects.get(qid=n)#usually ek hi result aayega woh bhi object hoga
        try:    
            if question.ans==request.POST['q'+str(n)] :
                total_right+=1
            else :
                total_wrong+=1
            total_attempt+=1
        except :
            pass
    
    points=(total_right-total_wrong)/len(qid_list)*10
    #store result in result table
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()
    #update candidate table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    return HttpResponseRedirect('result')
        

def testResultHistory(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect('login')
        return res
    candidate=Candidate.objects.get(username=request.session['username'])
    result=Result.objects.filter(username_id=candidate.username)
    context={
        'candidate':candidate,
        'results':result,
    }
    res=render(request,'candidate_history.html',context)
    return res

def showTestResult(request):
    if 'name' not in request.session.keys():#ye code har baar check krega goi unothorized entry chah raha hai kya 
        res=HttpResponseRedirect('login')
        return res
    #fetch latest result form result table
    result=Result.objects.filter(result=Result.objects.latest('result').result,username=request.session['username'])
    context={
        'result':result,
    }
    res=render(request,"show_result.html",context)
    return res


def logoutView(request):
    del request.session['username']
    del request.session['name']
    logout(request)#destroy sesssion variables
    return HttpResponseRedirect('login')

OTS/templates/candidate_history.html
{% extends 'main.html'%}

{% block title%}
OTS - Candidate Result History
{% endblock title%}

{% block top%}
<a href="{% url 'OTS:userhome' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock%}

{% block content %}
<h1>Your Report Card</h1>
<p>Hi {{candidate.username}}, you have attempted in Total {{candidate.test_attempted}} tests and you have scored {{candidate.points}} out of 10</p>

<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attemp</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in results %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attemp}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

OTS/templates/home.html
{% extends 'main.html'%}
{% load 'static' %}

{% block title%}
OTS - Candidate Home Page
{% endblock title%}

{% block top%}
<a href="{% url 'OTS:logout' %}">Log Out</a>
{% endblock%}

{% block content %}
<h1>Welcome {{ name }} to your Home Page</h1>
<div class="button-link">
    <a href="{% url 'OTS:testpaper' %}?n=1">Test of 1 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testpaper' %}?n=3">Test of 3 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testpaper' %}?n=5">Test of 5 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testHistory' %}">Test History</a>
</div>


{% endblock %}

OTS/templates/login.html
{% extends 'main.html'%}

{% block title%}
OTS - Login Form
{% endblock title%}

{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Sign Up</a>
{% endblock%}

{% block content %}
<div class="all-forms">
    {% if loginError %}
           <div class="error">{{ loginError }}</div>
    {% endif %}
    <form action="{% url 'OTS:login' %}" method="post">
        {% csrf_token%}
      <div class="form-unit">
        <label for="username">Username : 
            <input type="text" name="username">
        </label>
      </div>
      <br>
      <div class="form-unit">
        <label for="password">Password : 
            <input type="password" name="password">
        </label>
      </div>
      <div class="form-unit">
        <input type="submit" name="" id="" value="Login">
        <input type="reset" name="" id="" value="Clear">
      </div>
    </form>
    New user <a href="{% url 'OTS:registrationForm' %}">Click Here</a>
</div>
{% endblock %}

OTS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="top">
      <div class="sitename">
        <h1>Online Testing System</h1>
      </div>
      <div class="menu">{% block top %} {% endblock %}</div>
    </div>
    <div class="content">{% block content %} {% endblock %}</div>
  </body>
</html>

OTS/templates/registration.html
{% extends 'main.html' %}

{% block title %}
OTS-Registration Status 

{% endblock %}

{% block top%}

<a href="{% url 'OTS:login' %}">Login</a>
{% endblock%}

{% block content %}

{% if userStatus == 1 %}
<div class="userStatus">
    Sorry, username already exists, Please try different Username
    <a href="{% url 'OTS:registrationForm' %}">Back to Candidate Registration form</a>

</div>

{% elif userStatus == 2 %}
<div class="userStatus">
    Congratulations!! ,User Created Successfully
    <a href="{% url 'OTS:login' %}">Login</a>



</div>





{% endif %}



{% endblock %}

OTS/templates/registration_form.html
{% extends 'main.html'%}

{% block title%} OTS-Registration Form {% endblock%} 

{% block top%}
    <a href="{% url 'OTS:login' %}">Login</a>
    {% endblock%} 
    
    {% block content %}
    <div class="all-forms">
        <form action="{% url 'OTS:storeCandidate' %}" method="post">
          <!-- form submit hone ke baad kaha jayega uska url hota hai action attribute mei -->
          {% csrf_token %}
          <label for="username"
            >Username :
            <input type="text" name="username" />
          </label>
          <br />
          <label for="password"
            >Password :
            <input type="password" name="password" />
          </label>
          <br />
          <label for="name"
            >Name :
            <input type="text" name="name" />
          </label>
          <br />
          <input type="submit" value="Submit" />
          <input type="reset" name="" id="" value="Clear" />
        </form>
        Already have an account, <a href="{% url 'OTS:login' %}">Click Here</a>
      </div>
    {% endblock %}
    

OTS/templates/show_result.html
{% extends 'main.html'%}

{% block title%}
OTS - Result Page
{% endblock title%}

{% block top%}
<a href="{% url 'OTS:userhome' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock%}

{% block content %}
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attemp</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in result %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attemp}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

OTS/templates/test_paper.html
{% extends 'main.html'%} {% block title%} OTS - Test Paper {% endblock title%}
{% block top%} {% endblock%} {% block content %}
<form action="{% url 'OTS:calculateTest' %}" method="post">
  {% csrf_token%} 
  {% for question in questions %}
  <div class="question">
    <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}" />
    {{question.que}}
    <div class="options">
      <input type="radio" name="q{{question.qid}}" value="a" />{{question.a}}
    </div>
    <div class="options">
      <input type="radio" name="q{{question.qid}}" value="b" />{{question.b}}
    </div>
    <div class="options">
      <input type="radio" name="q{{question.qid}}" value="c" />{{question.c}}
    </div>
    <div class="options">
      <input type="radio" name="q{{question.qid}}" value="d" />{{question.d}}
      <!-- name must be same -->
    </div>
  </div>
  {% endfor %}
  <div><input type="submit" value="submit" name="" id="" /></div>
</form>
{% endblock %}

OTS/templates/welcome.html
{% extends 'main.html'%}

{% block title%}
Welcome to Online Testing System
{% endblock title%}

{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Sign Up</a>
<a href="{% url 'OTS:login' %}">Login</a>
{% endblock%}

{% block content %}
<p>Welcome to Online Testing System</p>
{% endblock %}